### ISSUE TITLE
No exit after mounting

### ISSUE THREAD

**Issue by Natetronn** [x1nixmzeng/xbox-iso-vfs#10]
Hello,

I'm using xbox-iso-vfs in a python app with PyQt6 Qprocess (think python subprocess, just for QT GUI) and when running xbox-iso-vfs I'm able to mount the xiso fine through my program, via your program & Dokan, but it doesn't seem to exit once mounted, so the next process in the queue isn't running thereafter (and the process after that, to manually unmount, isn't either.) 

I don't need a full exit (or for it to unmount), as I want it to stay mounted until I'm done working with it, but I do need it to send some sort of exit or complete signal, this so the next process in the queue can proceed. Then I'll unmount manually using the command: dokanctl /u some/path/to/iso etc.

That said, do you happen to know if this is an xbox-iso-vfs issue or a Dokan (Dokan FUSE?) issue?

**Comment by Natetronn** [comment]
It doesn't exit when using xbox-iso-vfs directly from the terminal either, like xbfuse does. The docs alludes to this and why it says: "Unmount with CTRL + C in the console or alternatively via "dokanctl /u mount_path." But wondering if it could be written to work more like xbfuse, where it runs and exits after initial mount, but stays mounted until one manually unmounts it.

**Comment by x1nixmzeng** [comment]
Hey, thanks for checking out the project!

Unfortunately it's not an issue, it's the intended and expected behaviour. The logic to support the xbox filesystem is implemented in the tool - the dokan library is initialised, and then it registers the callbacks needed to respond to the driver which must which exist for the lifetime of the mount point is active.

I suggest for your GUI wrapper you run xbox-iso-vfs as a background task - keep it running until it exists - when unmounting has occurred (or there is an error)

**Comment by Natetronn** [comment]
Thanks for the reply and the suggestion! I'll look into it...
